---
title: "Three Visualizations"
subtitle: "Data Visualization (STAT 302)" 
author: "Gian Mella"
format:
  html:
    toc: true
    embed-resources: true
    code-fold: show
    link-external-newwindow: true
    fig-dpi: 300
execute:
  warning: false
from: markdown+emoji 
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggthemes)
library(dplyr)
library(patchwork)
library(ggrepel)

load(file = "data/processed/bball_data1.rda")
```

```{r}
# first plot

# create rank function

quartile_rank <- function(x = 0:99) {
  # Set quartile
  quart_breaks <- c(
    -Inf,
    quantile(x,
             probs = c(.25, .5, .75),
             na.rm = TRUE
    ),
    Inf
  )
  cut(x = x, breaks = quart_breaks, labels = FALSE)
}

# reverse defensive rating to fit into quartile rank function

new_bball_data1 <- bball_data1 %>%
  mutate(rank = dense_rank(desc(d_rtg)))

jimmy_circle_adv <- new_bball_data1 %>%
  mutate(
    per_quant = quartile_rank(per),
    vorp_quant = quartile_rank(vorp),
    bpm_quant = quartile_rank(bpm),
    o_rtg_quant = quartile_rank(o_rtg),
    d_rtg_quant = quartile_rank(rank)
  ) %>%
  select(player, contains("_quant")) %>%
  pivot_longer(
    cols = -player,
    names_to = "variable",
    values_to = "value"
  ) %>%
  arrange(player)
```


```{r}
#| fig-width: 25
#| fig-height: 25

p1 <- jimmy_circle_adv %>%
filter(player == "Jimmy Butler") %>%
  ggplot(aes(variable, value)) +
  geom_col(width = 1, fill = "red2") +
  # placing dotted lines
  geom_hline(yintercept = 1:4, linetype = "dotted") +
  geom_segment(x = 0.5:4.5, y = 0, xend = 0.5:4.5, yend = 4) +
  ggtitle("Jimmy Butler") +
  scale_x_discrete(
    name = NULL,
    expand = c(0, 0),
    limits = c("per_quant", "vorp_quant", "bpm_quant", "o_rtg_quant", "d_rtg_quant")
  ) +
  scale_y_continuous(
    name = NULL, 
    expand = c(0, 0)
  ) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 30),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_line(color = NA)
  ) +
  # sector labels
  annotate(
    geom = "text",
    label = c("PLAYER EFFICIENCY\nRATING", "   VALUE OVER\n   REPLACEMENT", "BOX\nPLUS-MINUS", "OFFENSIVE\nRATING", "DEFENSIVE\nRATING"),
    x = 1:5,
    y = 5,
    size = 6
  ) +
  annotate(
    geom = "text",
    label = c("1st-25th","25th-50th", "50th-75th", "75th-99th"),
    x = 3,
    y = 0.7:3.7,
    size = 5
  ) + 
  coord_polar()

p2 <- jimmy_circle_adv %>%
filter(player == "Jayson Tatum") %>%
  ggplot(aes(variable, value)) +
  geom_col(width = 1, fill = "green3") +
  # placing dotted lines
  geom_hline(yintercept = 1:4, linetype = "dotted") +
  geom_segment(x = 0.5:4.5, y = 0, xend = 0.5:4.5, yend = 4) +
  ggtitle("Jayson Tatum") +
  scale_x_discrete(
    name = NULL,
    expand = c(0, 0),
    limits = c("per_quant", "vorp_quant", "bpm_quant", "o_rtg_quant", "d_rtg_quant")
  ) +
  scale_y_continuous(
    name = NULL, 
    expand = c(0, 0)
  ) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 30),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_line(color = NA)
  ) +
  # sector labels
  annotate(
    geom = "text",
    label = c("PLAYER EFFICIENCY\nRATING", "   VALUE OVER\n   REPLACEMENT", "BOX\nPLUS-MINUS", "OFFENSIVE\nRATING", "DEFENSIVE\nRATING"),
    x = 1:5,
    y = 5,
    size = 6
  ) +
  annotate(
    geom = "text",
    label = c("1st-25th","25th-50th", "50th-75th", "75th-99th"),
    x = 3,
    y = 0.7:3.7,
    size = 5
  ) + 
  coord_polar()

p3 <- jimmy_circle_adv %>%
filter(player == "Stephen Curry") %>%
  ggplot(aes(variable, value)) +
  geom_col(width = 1, fill = "yellow1") +
  # placing dotted lines
  geom_hline(yintercept = 1:4, linetype = "dotted") +
  geom_segment(x = 0.5:4.5, y = 0, xend = 0.5:4.5, yend = 4) +
  ggtitle("Stephen Curry") +
  scale_x_discrete(
    name = NULL,
    expand = c(0, 0),
    limits = c("per_quant", "vorp_quant", "bpm_quant", "o_rtg_quant", "d_rtg_quant")
  ) +
  scale_y_continuous(
    name = NULL, 
    expand = c(0, 0)
  ) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 30),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_line(color = NA)
  ) +
  # sector labels
  annotate(
    geom = "text",
    label = c("PLAYER EFFICIENCY\nRATING", "   VALUE OVER\n   REPLACEMENT", "BOX\nPLUS-MINUS", "OFFENSIVE\nRATING", "DEFENSIVE\nRATING"),
    x = 1:5,
    y = 5,
    size = 6
  ) +
  annotate(
    geom = "text",
    label = c("1st-25th","25th-50th", "50th-75th", "75th-99th"),
    x = 3,
    y = 0.7:3.7,
    size = 5
  ) + 
  coord_polar()

p4 <- jimmy_circle_adv %>%
filter(player == "Luka Dončić") %>%
  ggplot(aes(variable, value)) +
  geom_col(width = 1, fill = "skyblue3") +
  # placing dotted lines
  geom_hline(yintercept = 1:4, linetype = "dotted") +
  geom_segment(x = 0.5:4.5, y = 0, xend = 0.5:4.5, yend = 4) +
  ggtitle("Luka Dončić") +
  scale_x_discrete(
    name = NULL,
    expand = c(0, 0),
    limits = c("per_quant", "vorp_quant", "bpm_quant", "o_rtg_quant", "d_rtg_quant")
  ) +
  scale_y_continuous(
    name = NULL, 
    expand = c(0, 0)
  ) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 30),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_line(color = NA)
  ) +
  # sector labels
  annotate(
    geom = "text",
    label = c("PLAYER EFFICIENCY\nRATING", "   VALUE OVER\n   REPLACEMENT", "BOX\nPLUS-MINUS", "OFFENSIVE\nRATING", "DEFENSIVE\nRATING"),
    x = 1:5,
    y = 5,
    size = 6
  ) +
  annotate(
    geom = "text",
    label = c("1st-25th","25th-50th", "50th-75th", "75th-99th"),
    x = 3,
    y = 0.7:3.7,
    size = 5
  ) + 
  coord_polar()

(p1 + p2) / (p3 + p4)

```

```{r}

table <- bball_data1 %>% 
  arrange(desc(pts)) %>% 
  head(n = 10) %>% 
  pivot_longer(c(`fg_percent`, `2p_percent`, `3p_percent`, `ft_percent`, `ts_percent`, `efg_percent`), names_to = "type", values_to = "shooting_percent") 


jimmy_comparison_efg <- table %>%
  mutate(is_top = ifelse(player == "Jimmy Butler", "Jimmy Butler", "Rest of Top 10")) %>%
  filter(type == "efg_percent") %>% 
  group_by(is_top) %>%
  summarize(`Effective Field Goal` = mean(`shooting_percent`),
            ) 

jimmy_comparison_ft <- table %>%
  mutate(is_top = ifelse(player == "Jimmy Butler", "Jimmy Butler", "Rest of Top 10")) %>%
  filter(type == "ft_percent") %>% 
  group_by(is_top) %>%
  summarize(`Free Throw` = mean(`shooting_percent`),
            ) 

jimmy_comparison_ts <- table %>%
  mutate(is_top = ifelse(player == "Jimmy Butler", "Jimmy Butler", "Rest of Top 10")) %>%
  filter(type == "ts_percent") %>% 
  group_by(is_top) %>%
  summarize(`True Shooting` = mean(`shooting_percent`),
            ) 

jimmy_comparison_fg <- table %>%
  mutate(is_top = ifelse(player == "Jimmy Butler", "Jimmy Butler", "Rest of Top 10")) %>%
  filter(type == "fg_percent") %>% 
  group_by(is_top) %>%
  summarize(`Field Goal` = mean(`shooting_percent`),
            ) 

jimmy_comparison_2p <- table %>%
  mutate(is_top = ifelse(player == "Jimmy Butler", "Jimmy Butler", "Rest of Top 10")) %>%
  filter(type == "2p_percent") %>% 
  group_by(is_top) %>%
  summarize(`Two Point` = mean(`shooting_percent`),
            ) 

jimmy_comparison_3p <- table %>%
  mutate(is_top = ifelse(player == "Jimmy Butler", "Jimmy Butler", "Rest of Top 10")) %>%
  filter(type == "3p_percent") %>% 
  group_by(is_top) %>%
  summarize(`Three Point` = mean(`shooting_percent`),
            ) 

jimmy_comparison_efg1 <- jimmy_comparison_efg %>% inner_join(jimmy_comparison_ts)

jimmy_comparison_efg2 <- jimmy_comparison_efg1 %>% inner_join(jimmy_comparison_ft)

jimmy_comparison_efg3 <- jimmy_comparison_efg2 %>% inner_join(jimmy_comparison_fg)

jimmy_comparison_efg4 <- jimmy_comparison_efg3 %>% inner_join(jimmy_comparison_2p)

jimmy_comparison_final <- jimmy_comparison_efg4 %>% inner_join(jimmy_comparison_3p)

```

```{r}
jimmy_comparison_tidy <- jimmy_comparison_final %>%
  pivot_longer(cols = !is_top, names_to = "var", values_to = "perc")

p5 <- ggplot(jimmy_comparison_tidy, aes(var, perc)) +
  geom_col(aes(fill = is_top), width = 0.5, position = "dodge") +
  scale_fill_manual(
    values = c("orangered3", "thistle3"),
    labels = c("Butler    ", "Average of PPG Leaders")
  ) +
  theme_minimal() +
  labs(
    x = NULL,
    y = "Percentage (%)",
    title = "Jimmy Butler Shooting Percentages vs. Rest of Top 10 Scorers\n                              (2022 NBA Playoffs)"
  ) +
  guides(
    fill = guide_legend(
      nrows = 1,
      override.aes = list(
        fill = c("orangered3", "thistle3"),
        color = "transparent")
      )
  ) +
  theme(
    legend.position = c(.8,.9),
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.3, size = 12),
    legend.direction = "horizontal"
  )

p5
```

```{r}
label_info <- subset(bball_data1, player == "Jimmy Butler")

yrng <- range(bball_data1$win_shares)
xrng <- range(bball_data1$games_played)


highlight_jimmy <- bball_data1 %>% mutate(highlight = ifelse(player == "Jimmy Butler", "yes", "no" ))

ggplot(highlight_jimmy, aes(games_played, win_shares)) +
  geom_point(aes(color = highlight), size = 2, show.legend = FALSE) +
  scale_color_manual(values = c("yes" = "firebrick3", "no" = "deepskyblue2"), guide = FALSE) + 
  geom_text_repel(
    data = label_info,
    aes(label = player),
    color = "darkslategray",
    box.padding = 0.6,
    min.segment.length = 0
  ) +
  geom_smooth(method = lm, color = "darkslategray", se = FALSE) +
  labs(
    x = "Games Played",
    y = "Total Win Shares",
  ) +
  annotate(
    geom = "text",
    x = xrng[1],
    y = yrng[2],
    label = "Individual Games Played vs. Win Shares\n              (2022 NBA Playoffs)",
    hjust = 0,
    vjust = 1,
    size = 4
  ) +
  theme_classic()
```


